wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1659962000.798798
    t:
      1:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 54
      - 55
      - 80
      2:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 54
      - 55
      - 80
      3:
      - 13
      - 23
      4: 3.7.13
      5: 0.13.1
      8:
      - 5
